# Generated by Django 4.1.2 on 2022-10-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Literature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "sub_title",
                    models.CharField(
                        help_text="Example: Edition of the literatures", max_length=50
                    ),
                ),
            ],
            options={
                "db_table": "literature",
            },
        ),
        migrations.CreateModel(
            name="LiteratureSubSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("sub_title", models.CharField(max_length=50)),
                ("is_sub_title_active", models.BooleanField(default=True)),
                ("main_content", models.TextField()),
                (
                    "literature_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="literature",
                        to="literature.literature",
                    ),
                ),
            ],
            options={
                "db_table": "literature_sub_section",
            },
        ),
    ]
