# Generated by Django 4.1.2 on 2022-11-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="literaturesubsection",
            name="end_page",
        ),
        migrations.RemoveField(
            model_name="literaturesubsection",
            name="start_page",
        ),
        migrations.AlterField(
            model_name="literaturesubsection",
            name="subtitle",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
