# Generated by Django 4.1.2 on 2022-10-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="literaturesubsection",
            old_name="literature_id",
            new_name="literature",
        ),
    ]
