# Generated by Django 4.1.2 on 2022-11-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="social_type",
            field=models.CharField(
                choices=[
                    ("fb", "Facebook Login"),
                    ("google", "Google Login"),
                    ("apple", "Apple Login"),
                    ("admin", "Admin Login"),
                ],
                max_length=6,
            ),
        ),
    ]
